url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Flora Lin" # the name of your site, e.g. ACME Corp.

imagesurl: "/assets/img/"
thumbsurl: "/assets/img/thumbs/"

collections:
  members:
    output: true
  lyrics:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "lyrics"
    values:
      layout: "member"
  - scope:
      path: ""
    values:
      layout: "default"
